connect:
  enabled: true
  name: anonmouse

config:

  bind: 0.0.0.0:25566

  onlineMode: false

  servers:
    server1: localhost:25565
  
  try:
    - server1

  status:
    motd: |
      §bServer Minecraft của Anonmouse ^^
      §bLưu ý: §fNếu vô lần đầu không được thì thử refresh rồi vô lại

    announceForge: true

proxyProtocol: true